# Generated by Django 5.2.16 on 2026-09-22 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0013_githubrun_config_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOpsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_enabled', models.BooleanField(default=False, verbose_name='维护模式')),
                ('maintenance_message', models.TextField(blank=True, default='生成器正在维护中，请稍后再试。', verbose_name='维护提示')),
                ('announcement', models.TextField(blank=True, default='', verbose_name='前台公告')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '站点运维配置',
                'verbose_name_plural': '站点运维配置',
            },
        ),
        migrations.AddField(
            model_name='activationcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='未使用激活码的过期时间；到期后自动作废。', null=True),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='failure_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='failure_summary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='disable_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.JSONField(blank=True, default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '超管操作审计',
                'verbose_name_plural': '超管操作审计',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', '注册验证码'), ('build_success', '构建成功通知'), ('test', 'SMTP 测试'), ('expiry_reminder', '会员到期提醒'), ('login_alert', '异地登录提醒')], db_index=True, max_length=32)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='rdgenerator.githubrun')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '邮件投递日志',
                'verbose_name_plural': '邮件投递日志',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('remote_alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登录事件',
                'verbose_name_plural': '登录事件',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to='rdgenerator.githubrun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '下载审计',
                'verbose_name_plural': '下载审计',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['run', 'created_at'], name='rdgen_dl_run_created_idx')],
            },
        ),
    ]
